---

- name: Install KVM-related packages
  apt:
    name: '{{ item }}'
    state: 'latest'
    install_recommends: False
  with_items: [ 'libvirt-bin', 'netcat-openbsd', 'gawk', 'qemu-system', 'pm-utils', 'ebtables' ]

- name: Add administrators to libvirt group
  user:
    name: '{{ item }}'
    groups: '{{ kvm_group }}'
    append: True
  with_items: [ '{{ kvm_admins }}' ]
  when: (kvm_admins is defined and kvm_admins)

- name: Configure firewall rules
  template:
    src: 'etc/ferm/ferm.d/kvm-forwarding.conf.j2'
    dest: '/etc/ferm/ferm.d/kvm-forwarding.conf'
    owner: 'root'
    group: 'adm'
    mode: '0644'
  notify: [ 'Restart ferm' ]

